import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../providers/theme-provider";
import { Toaster } from "@/components/ui/toaster";
import { CurrentUserStoreProvider } from "@/providers/auth-store-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster />
        <ThemeProvider
          attribute="class"
          forcedTheme="dark"
          storageKey="streamline-theme"
        >
          <CurrentUserStoreProvider>{children}</CurrentUserStoreProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
